//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("BuyAHouseDataEntities", "FK_PropertyOffer", "Property1", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(BuyAHouse.Data.Property), "Offer", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(BuyAHouse.Data.Offer), true)]

#endregion

namespace BuyAHouse.Data
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class BuyAHouseDataEntitiesContainer : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new BuyAHouseDataEntitiesContainer object using the connection string found in the 'BuyAHouseDataEntitiesContainer' section of the application configuration file.
        /// </summary>
        public BuyAHouseDataEntitiesContainer() : base("name=BuyAHouseDataEntitiesContainer", "BuyAHouseDataEntitiesContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new BuyAHouseDataEntitiesContainer object.
        /// </summary>
        public BuyAHouseDataEntitiesContainer(string connectionString) : base(connectionString, "BuyAHouseDataEntitiesContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new BuyAHouseDataEntitiesContainer object.
        /// </summary>
        public BuyAHouseDataEntitiesContainer(EntityConnection connection) : base(connection, "BuyAHouseDataEntitiesContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Offer> Offers
        {
            get
            {
                if ((_Offers == null))
                {
                    _Offers = base.CreateObjectSet<Offer>("Offers");
                }
                return _Offers;
            }
        }
        private ObjectSet<Offer> _Offers;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Property> Properties
        {
            get
            {
                if ((_Properties == null))
                {
                    _Properties = base.CreateObjectSet<Property>("Properties");
                }
                return _Properties;
            }
        }
        private ObjectSet<Property> _Properties;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Offers EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToOffers(Offer offer)
        {
            base.AddObject("Offers", offer);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Properties EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToProperties(Property property)
        {
            base.AddObject("Properties", property);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BuyAHouseDataEntities", Name="Offer")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Offer : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Offer object.
        /// </summary>
        /// <param name="offerId">Initial value of the OfferId property.</param>
        /// <param name="buyerName">Initial value of the BuyerName property.</param>
        /// <param name="requestId">Initial value of the RequestId property.</param>
        /// <param name="emailAddress">Initial value of the EmailAddress property.</param>
        /// <param name="amount">Initial value of the Amount property.</param>
        /// <param name="propertyId">Initial value of the PropertyId property.</param>
        /// <param name="accepted">Initial value of the Accepted property.</param>
        public static Offer CreateOffer(global::System.Int32 offerId, global::System.String buyerName, global::System.Guid requestId, global::System.String emailAddress, global::System.Decimal amount, global::System.Int32 propertyId, global::System.Boolean accepted)
        {
            Offer offer = new Offer();
            offer.OfferId = offerId;
            offer.BuyerName = buyerName;
            offer.RequestId = requestId;
            offer.EmailAddress = emailAddress;
            offer.Amount = amount;
            offer.PropertyId = propertyId;
            offer.Accepted = accepted;
            return offer;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 OfferId
        {
            get
            {
                return _OfferId;
            }
            set
            {
                if (_OfferId != value)
                {
                    OnOfferIdChanging(value);
                    ReportPropertyChanging("OfferId");
                    _OfferId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("OfferId");
                    OnOfferIdChanged();
                }
            }
        }
        private global::System.Int32 _OfferId;
        partial void OnOfferIdChanging(global::System.Int32 value);
        partial void OnOfferIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String BuyerName
        {
            get
            {
                return _BuyerName;
            }
            set
            {
                OnBuyerNameChanging(value);
                ReportPropertyChanging("BuyerName");
                _BuyerName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("BuyerName");
                OnBuyerNameChanged();
            }
        }
        private global::System.String _BuyerName;
        partial void OnBuyerNameChanging(global::System.String value);
        partial void OnBuyerNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid RequestId
        {
            get
            {
                return _RequestId;
            }
            set
            {
                OnRequestIdChanging(value);
                ReportPropertyChanging("RequestId");
                _RequestId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RequestId");
                OnRequestIdChanged();
            }
        }
        private global::System.Guid _RequestId;
        partial void OnRequestIdChanging(global::System.Guid value);
        partial void OnRequestIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String EmailAddress
        {
            get
            {
                return _EmailAddress;
            }
            set
            {
                OnEmailAddressChanging(value);
                ReportPropertyChanging("EmailAddress");
                _EmailAddress = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("EmailAddress");
                OnEmailAddressChanged();
            }
        }
        private global::System.String _EmailAddress;
        partial void OnEmailAddressChanging(global::System.String value);
        partial void OnEmailAddressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal Amount
        {
            get
            {
                return _Amount;
            }
            set
            {
                OnAmountChanging(value);
                ReportPropertyChanging("Amount");
                _Amount = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Amount");
                OnAmountChanged();
            }
        }
        private global::System.Decimal _Amount;
        partial void OnAmountChanging(global::System.Decimal value);
        partial void OnAmountChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 PropertyId
        {
            get
            {
                return _PropertyId;
            }
            set
            {
                OnPropertyIdChanging(value);
                ReportPropertyChanging("PropertyId");
                _PropertyId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PropertyId");
                OnPropertyIdChanged();
            }
        }
        private global::System.Int32 _PropertyId;
        partial void OnPropertyIdChanging(global::System.Int32 value);
        partial void OnPropertyIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Accepted
        {
            get
            {
                return _Accepted;
            }
            set
            {
                OnAcceptedChanging(value);
                ReportPropertyChanging("Accepted");
                _Accepted = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Accepted");
                OnAcceptedChanged();
            }
        }
        private global::System.Boolean _Accepted;
        partial void OnAcceptedChanging(global::System.Boolean value);
        partial void OnAcceptedChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BuyAHouseDataEntities", "FK_PropertyOffer", "Property1")]
        public Property Property
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Property>("BuyAHouseDataEntities.FK_PropertyOffer", "Property1").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Property>("BuyAHouseDataEntities.FK_PropertyOffer", "Property1").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Property> PropertyReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Property>("BuyAHouseDataEntities.FK_PropertyOffer", "Property1");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Property>("BuyAHouseDataEntities.FK_PropertyOffer", "Property1", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BuyAHouseDataEntities", Name="Property")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Property : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Property object.
        /// </summary>
        /// <param name="propertyId">Initial value of the PropertyId property.</param>
        /// <param name="address">Initial value of the Address property.</param>
        public static Property CreateProperty(global::System.Int32 propertyId, global::System.String address)
        {
            Property property = new Property();
            property.PropertyId = propertyId;
            property.Address = address;
            return property;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 PropertyId
        {
            get
            {
                return _PropertyId;
            }
            set
            {
                if (_PropertyId != value)
                {
                    OnPropertyIdChanging(value);
                    ReportPropertyChanging("PropertyId");
                    _PropertyId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("PropertyId");
                    OnPropertyIdChanged();
                }
            }
        }
        private global::System.Int32 _PropertyId;
        partial void OnPropertyIdChanging(global::System.Int32 value);
        partial void OnPropertyIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Address
        {
            get
            {
                return _Address;
            }
            set
            {
                OnAddressChanging(value);
                ReportPropertyChanging("Address");
                _Address = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Address");
                OnAddressChanged();
            }
        }
        private global::System.String _Address;
        partial void OnAddressChanging(global::System.String value);
        partial void OnAddressChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BuyAHouseDataEntities", "FK_PropertyOffer", "Offer")]
        public EntityCollection<Offer> Offers
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Offer>("BuyAHouseDataEntities.FK_PropertyOffer", "Offer");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Offer>("BuyAHouseDataEntities.FK_PropertyOffer", "Offer", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
