//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuyAHouse.OfferService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://buyahouse.com/contracts/", ConfigurationName="OfferService.IService")]
    public interface IService {
        
        // CODEGEN: Generating message contract since the operation BuyerOffer is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://buyahouse.com/contracts/IService/BuyerOffer", ReplyAction="http://buyahouse.com/contracts/IService/BuyerOfferResponse")]
        BuyAHouse.OfferService.BuyerOfferResponse BuyerOffer(BuyAHouse.OfferService.BuyerOfferRequest request);
        
        // CODEGEN: Generating message contract since the operation SellerOffer is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://buyahouse.com/contracts/IService/SellerOffer", ReplyAction="http://buyahouse.com/contracts/IService/SellerOfferResponse")]
        BuyAHouse.OfferService.SellerOfferResponse SellerOffer(BuyAHouse.OfferService.SellerOfferRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BuyerOfferRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://buyahouse.com/contracts", Order=0)]
        public BuyAHouse.Contracts.SubmitOfferRequest SubmitOfferRequest;
        
        public BuyerOfferRequest() {
        }
        
        public BuyerOfferRequest(BuyAHouse.Contracts.SubmitOfferRequest SubmitOfferRequest) {
            this.SubmitOfferRequest = SubmitOfferRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BuyerOfferResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://buyahouse.com/contracts", Order=0)]
        public BuyAHouse.Contracts.SubmitOfferResponse SubmitOfferResponse;
        
        public BuyerOfferResponse() {
        }
        
        public BuyerOfferResponse(BuyAHouse.Contracts.SubmitOfferResponse SubmitOfferResponse) {
            this.SubmitOfferResponse = SubmitOfferResponse;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SellerOfferRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://buyahouse.com/contracts", Order=0)]
        public BuyAHouse.Contracts.OfferAcceptanceResult OfferAcceptanceResult;
        
        public SellerOfferRequest() {
        }
        
        public SellerOfferRequest(BuyAHouse.Contracts.OfferAcceptanceResult OfferAcceptanceResult) {
            this.OfferAcceptanceResult = OfferAcceptanceResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SellerOfferResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.microsoft.com/2003/10/Serialization/", Order=0)]
        public System.Nullable<bool> boolean;
        
        public SellerOfferResponse() {
        }
        
        public SellerOfferResponse(System.Nullable<bool> boolean) {
            this.boolean = boolean;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : BuyAHouse.OfferService.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<BuyAHouse.OfferService.IService>, BuyAHouse.OfferService.IService {
        
        public ServiceClient() {
        }
        
        public ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BuyAHouse.OfferService.BuyerOfferResponse BuyAHouse.OfferService.IService.BuyerOffer(BuyAHouse.OfferService.BuyerOfferRequest request) {
            return base.Channel.BuyerOffer(request);
        }
        
        public BuyAHouse.Contracts.SubmitOfferResponse BuyerOffer(BuyAHouse.Contracts.SubmitOfferRequest SubmitOfferRequest) {
            BuyAHouse.OfferService.BuyerOfferRequest inValue = new BuyAHouse.OfferService.BuyerOfferRequest();
            inValue.SubmitOfferRequest = SubmitOfferRequest;
            BuyAHouse.OfferService.BuyerOfferResponse retVal = ((BuyAHouse.OfferService.IService)(this)).BuyerOffer(inValue);
            return retVal.SubmitOfferResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BuyAHouse.OfferService.SellerOfferResponse BuyAHouse.OfferService.IService.SellerOffer(BuyAHouse.OfferService.SellerOfferRequest request) {
            return base.Channel.SellerOffer(request);
        }
        
        public System.Nullable<bool> SellerOffer(BuyAHouse.Contracts.OfferAcceptanceResult OfferAcceptanceResult) {
            BuyAHouse.OfferService.SellerOfferRequest inValue = new BuyAHouse.OfferService.SellerOfferRequest();
            inValue.OfferAcceptanceResult = OfferAcceptanceResult;
            BuyAHouse.OfferService.SellerOfferResponse retVal = ((BuyAHouse.OfferService.IService)(this)).SellerOffer(inValue);
            return retVal.boolean;
        }
    }
}
