//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuyAHouse.OfferService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://buyahouse.com/contracts/", ConfigurationName="OfferService.IService")]
    public interface IService {
        
        // CODEGEN: Generating message contract since the operation SubmitOffer is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://buyahouse.com/contracts/IService/SubmitOffer", ReplyAction="http://buyahouse.com/contracts/IService/SubmitOfferResponse")]
        BuyAHouse.OfferService.SubmitOfferResponse SubmitOffer(BuyAHouse.OfferService.SubmitOfferRequest request);
        
        // CODEGEN: Generating message contract since the operation SellerAcceptanceCompleted is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://buyahouse.com/contracts/IService/SellerAcceptanceCompleted", ReplyAction="http://buyahouse.com/contracts/IService/SellerAcceptanceCompletedResponse")]
        BuyAHouse.OfferService.SellerAcceptanceCompletedResponse SellerAcceptanceCompleted(BuyAHouse.OfferService.SellerAcceptanceCompletedRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SubmitOfferRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SubmitOfferRequest", Namespace="http://buyahouse.com/contracts", Order=0)]
        public BuyAHouse.Contracts.SubmitOfferRequest SubmitOfferRequest1;
        
        public SubmitOfferRequest() {
        }
        
        public SubmitOfferRequest(BuyAHouse.Contracts.SubmitOfferRequest SubmitOfferRequest1) {
            this.SubmitOfferRequest1 = SubmitOfferRequest1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SubmitOfferResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SubmitOfferResponse", Namespace="http://buyahouse.com/contracts", Order=0)]
        public BuyAHouse.Contracts.SubmitOfferResponse SubmitOfferResponse1;
        
        public SubmitOfferResponse() {
        }
        
        public SubmitOfferResponse(BuyAHouse.Contracts.SubmitOfferResponse SubmitOfferResponse1) {
            this.SubmitOfferResponse1 = SubmitOfferResponse1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SellerAcceptanceCompletedRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://buyahouse.com/contracts", Order=0)]
        public BuyAHouse.Contracts.SellerAcceptanceResult SellerAcceptanceResult;
        
        public SellerAcceptanceCompletedRequest() {
        }
        
        public SellerAcceptanceCompletedRequest(BuyAHouse.Contracts.SellerAcceptanceResult SellerAcceptanceResult) {
            this.SellerAcceptanceResult = SellerAcceptanceResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SellerAcceptanceCompletedResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.microsoft.com/2003/10/Serialization/", Order=0)]
        public System.Nullable<bool> boolean;
        
        public SellerAcceptanceCompletedResponse() {
        }
        
        public SellerAcceptanceCompletedResponse(System.Nullable<bool> boolean) {
            this.boolean = boolean;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : BuyAHouse.OfferService.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<BuyAHouse.OfferService.IService>, BuyAHouse.OfferService.IService {
        
        public ServiceClient() {
        }
        
        public ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BuyAHouse.OfferService.SubmitOfferResponse BuyAHouse.OfferService.IService.SubmitOffer(BuyAHouse.OfferService.SubmitOfferRequest request) {
            return base.Channel.SubmitOffer(request);
        }
        
        public BuyAHouse.Contracts.SubmitOfferResponse SubmitOffer(BuyAHouse.Contracts.SubmitOfferRequest SubmitOfferRequest1) {
            BuyAHouse.OfferService.SubmitOfferRequest inValue = new BuyAHouse.OfferService.SubmitOfferRequest();
            inValue.SubmitOfferRequest1 = SubmitOfferRequest1;
            BuyAHouse.OfferService.SubmitOfferResponse retVal = ((BuyAHouse.OfferService.IService)(this)).SubmitOffer(inValue);
            return retVal.SubmitOfferResponse1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BuyAHouse.OfferService.SellerAcceptanceCompletedResponse BuyAHouse.OfferService.IService.SellerAcceptanceCompleted(BuyAHouse.OfferService.SellerAcceptanceCompletedRequest request) {
            return base.Channel.SellerAcceptanceCompleted(request);
        }
        
        public System.Nullable<bool> SellerAcceptanceCompleted(BuyAHouse.Contracts.SellerAcceptanceResult SellerAcceptanceResult) {
            BuyAHouse.OfferService.SellerAcceptanceCompletedRequest inValue = new BuyAHouse.OfferService.SellerAcceptanceCompletedRequest();
            inValue.SellerAcceptanceResult = SellerAcceptanceResult;
            BuyAHouse.OfferService.SellerAcceptanceCompletedResponse retVal = ((BuyAHouse.OfferService.IService)(this)).SellerAcceptanceCompleted(inValue);
            return retVal.boolean;
        }
    }
}
