//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuyAHouse.Activities {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ServiceResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ServiceResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BuyAHouse.Activities.ServiceResources", typeof(ServiceResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;title&gt;&lt;/title&gt;
        ///    &lt;style type=&quot;text/css&quot;&gt;
        ///        body
        ///        {{
        ///            font-family: Verdana;
        ///            font-size: large;
        ///        }}
        ///        &lt;/style&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///&lt;img src=&quot;{2}/Content/logo.png&quot; alt=&quot;BuyAHome Logo&quot; /&gt;
        ///&lt;h2&gt;{0}&lt;/h2&gt;
        ///&lt;p&gt;{1}&lt;/p&gt;
        ///
        ///&lt;/body&gt;
        ///&lt;/html&gt;.
        /// </summary>
        public static string GenericMailTemplate {
            get {
                return ResourceManager.GetString("GenericMailTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Congratulations.
        /// </summary>
        public static string OfferAcceptedHeading {
            get {
                return ResourceManager.GetString("OfferAcceptedHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear {0}, we wanted to let you know that your offer has been accepted.  We will call you shortly to start getting a mortgage settled..
        /// </summary>
        public static string OfferAcceptedText {
            get {
                return ResourceManager.GetString("OfferAcceptedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We&apos;re sorry.
        /// </summary>
        public static string OfferDeniedHeading {
            get {
                return ResourceManager.GetString("OfferDeniedHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear {0}, we regret to inform you that your offer has been denied.  You may feel free to submit another offer, and try again..
        /// </summary>
        public static string OfferDeniedText {
            get {
                return ResourceManager.GetString("OfferDeniedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;title&gt;&lt;/title&gt;
        ///    &lt;style type=&quot;text/css&quot;&gt;
        ///        body
        ///        {{
        ///            font-family: Verdana;
        ///            font-size: large;
        ///        }}
        ///        &lt;/style&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///&lt;img src=&quot;{2}/Content/logo.png&quot; alt=&quot;BuyAHome Logo&quot; /&gt;
        ///&lt;h2&gt;Action Required&lt;/h2&gt;
        ///&lt;p&gt;An offer from {0} has been made on your house!  Please review the details and make a decision.&lt;/p&gt;
        ///&lt;p&gt;&lt;a href=&quot;{2}/Offer/Details/{1}&quot;&gt;Review the offer&lt;/a&gt;&lt;/p&gt;
        ///&lt;/body&gt;
        ///&lt;/html&gt;.
        /// </summary>
        public static string OfferMadeToSeller {
            get {
                return ResourceManager.GetString("OfferMadeToSeller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you {0}, your offer Id is {1}. We are now processing your offer.  You will receive an email with the results once a decision has been made by the seller..
        /// </summary>
        public static string OfferProcessing {
            get {
                return ResourceManager.GetString("OfferProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An offer has been made by {0}.
        /// </summary>
        public static string OfferProcessingSubject {
            get {
                return ResourceManager.GetString("OfferProcessingSubject", resourceCulture);
            }
        }
    }
}
